### ISSUE TITLE
Look at Cadence Workflow

### ISSUE THREAD

**Issue by mfateev** [bserdar/watermelon#1]
I would recommend looking at the [Cadence Workflow](https://cadenceworkflow.io/) to make your tool fault tolerant. HashiCorp and BanzaiCloud already using it for their tools.

**Comment by bserdar** [comment]
Interesting. This is a much lower level tool than that, though. The purpose is the opposite of providing a high-level workflow, it is to provide a low-level tool to ssh into remote machines and do things with them.

**Comment by mfateev** [comment]
I see. Thanks for the explanation.
