### ISSUE TITLE
Go mod and vendor dependencies

### ISSUE THREAD

**Issue by dhiemaz** [bserdar/watermelon#2]
Hi @bserdar,
for vendoring, is there any reason that you put third-party dependencies along with your main source code ? Go modules was introduced in Go 1.11 for dependencies management and maybe you can consider to use it.

**Comment by bserdar** [comment]
I have a pull request for the scp library for sudo support. That's the reason for vendoring. Once (if) the author of that library accepts the PR, then I'll remove the vendor.

**Comment by dhiemaz** [comment]
Ah ok.. nice.. (y)

**Comment by bserdar** [comment]
fyi, figured out to get rid of that vendor dir using replace in go.mod.
